apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: robot-telemetry
  namespace: kafka
  labels:
    strimzi.io/cluster: robofleet
spec:
  partitions: 6
  replicas: 1
  config:
    retention.ms: "86400000"
    cleanup.policy: delete
